boundary_conditions = [ "species", "bc_input", "domain",]
eulerian_model = [ "model", "species", "date",]
flux = [ "species", "source", "domain", "database", "database_version", "model",]
footprints = [ "site", "model", "inlet", "domain", "time_resolved", "high_spatial_resolution", "short_lifetime", "species", "met_model",]
column = [ "satellite", "selection", "domain", "site", "species", "network",]
surface = [ "species", "site", "sampling_period", "station_long_name", "inlet", "instrument", "network", "source_format", "data_source", "icos_data_level", "data_type",]
