name: openghg_dev_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python>=3.8
  - git
  - flake8
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - requests-mock
  - pytest-tornasync
  - mypy==1.4.0
  - types-paramiko
  - types-PyYAML
  - types-requests
  - types-toml
  - types-urllib3
  - pip:
    - cfchecker @ git+https://github.com/openghg/cf-checker@master#egg=cf-checker
    - msgpack-types
