name: openghg_dev_env
channels:
  - openghg
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python>=3.9
  - conda-build
  - addict
  - cf_xarray
  - dask
  - h5netcdf
  - filelock
  - matplotlib
  - msgpack-python
  - netcdf4<=1.6.5
  - nbformat
  - numexpr
  - numpy<2.0
  - nc-time-axis
  - openghg_defs
  - openpyxl
  - pandas>=2.0
  - pip
  - plotly
  - pyvis
  - rapidfuzz
  - requests>=2.25
  - scipy
  - setuptools
  - tinydb
  - toml
  - rich
  - ipywidgets
  - xarray>=2025.04.0
  - rich
  - urllib3>=1.26.3
  - xesmf>=0.7
  - zarr==2.18.3
  - numcodecs
  - git
  - flake8
  - pint
  - pint-xarray
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - requests-mock
  - pytest-tornasync
  - mypy==1.7.1
  - tox>=4.24
  - types-PyYAML
  - types-requests
  - types-toml
  - types-urllib3
  - openghg_calscales
  - cdsapi
  - pip:
      - cfchecker @ git+https://github.com/openghg/cf-checker@master#egg=cf-checker
      - msgpack-types
      - icoscp
      - pytest-timeout
