name: openghg_dev_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python>=3.8
  - addict
  - dask
  - h5netcdf
  - matplotlib
  - msgpack-python
  - netcdf4
  - nbformat
  - numexpr
  - numpy
  - nc-time-axis
  - openghg_defs
  - pandas<2.0
  - pip
  - plotly
  - pyvis
  - rapidfuzz
  - requests>=2.25
  - scipy
  - tinydb
  - toml
  - tqdm
  - xarray
  - rich
  - urllib3>=1.26.3
  - xesmf>=0.7
  - git
  - flake8
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-mock
  - requests-mock
  - pytest-tornasync
  - mypy==1.4.0
  - types-PyYAML
  - types-requests
  - types-toml
  - types-urllib3
  - pip:
    - cfchecker @ git+https://github.com/openghg/cf-checker@master#egg=cf-checker
    - msgpack-types
    - icoscp
