"""
Utility functions for OpenGHG.
"""

from importlib import import_module as _import_module
from typing import Any

__all__ = [
    "cli",
    "combine_and_elevate_inlet",
    "combine_data_objects",
    "combine_multisite",
    "openghg_data_path",
    "format_data_level",
    "get_domain_info",
    "find_domain",
    "find_coord_name",
    "convert_lon_to_180",
    "convert_lon_to_360",
    "convert_internal_longitude",
    "cut_data_extent",
    "align_lat_lon",
    "download_data",
    "parse_url_filename",
    "to_dashboard",
    "to_dashboard_mobile",
    "check_filepath",
    "compress",
    "compress_json",
    "compress_str",
    "decompress",
    "decompress_json",
    "decompress_str",
    "get_datapath",
    "get_logfile_path",
    "load_json",
    "load_internal_json",
    "load_standardise_parser",
    "load_transform_parser",
    "read_header",
    "open_nc_fn",
    "open_time_nc_fn",
    "preprocess_nc_data",
    "get_data",
    "split_function_inputs",
    "format_inlet",
    "extract_inlet_value",
    "extract_height_name",
    "null_metadata_values",
    "not_set_metadata_values",
    "remove_null_keys",
    "check_number_match",
    "check_str_match",
    "check_value_match",
    "check_not_set_value",
    "get_overlap_keys",
    "merge_dict",
    "merge_and_extend_dict",
    "define_platform",
    "format_platform",
    "get_platform_from_info",
    "get_parameters",
    "AutoRegistry",
    "Registry",
    "update_scale",
    "get_site_info",
    "sites_in_network",
    "_get_site_data",
    "get_species_info",
    "synonyms",
    "species_lifetime",
    "check_lifetime_monthly",
    "check_species_lifetime",
    "check_species_time_resolved",
    "molar_mass",
    "clean_string",
    "extract_float",
    "is_number",
    "remove_punctuation",
    "to_lowercase",
    "check_and_set_null_variable",
    "check_date",
    "check_nan",
    "closest_daterange",
    "combine_dateranges",
    "create_daterange",
    "create_daterange_str",
    "create_frequency_str",
    "daterange_contains",
    "daterange_from_str",
    "daterange_overlap",
    "dates_overlap",
    "daterange_to_str",
    "evaluate_sampling_period",
    "find_daterange_gaps",
    "find_duplicate_timestamps",
    "first_last_dates",
    "get_dataset_daterange",
    "get_representative_daterange_str",
    "in_daterange",
    "parse_period",
    "dates_in_range",
    "relative_time_offset",
    "has_monthly_period",
    "infer_frequency",
    "sanitise_daterange",
    "split_daterange_str",
    "split_encompassed_daterange",
    "time_offset",
    "time_offset_definition",
    "timestamp_epoch",
    "timestamp_now",
    "timestamp_tzaware",
    "trim_daterange",
    "valid_daterange",
    "create_config",
    "get_user_id",
    "get_user_config_path",
    "read_local_config",
    "check_config",
    "handle_direct_store_path",
    "find_matching_site",
    "normalise_to_filepath_list",
    "multiple_inlets",
    "pairwise",
    "site_code_finder",
    "sort_by_filenames",
    "unanimous",
    "verify_site",
    "verify_site_with_satellite",
    "check_unique",
    "find_repeats",
    "collate_strings",
    "assign_units",
    "cf_ureg",
    "enable_pint_xarray",
    "show_versions",
    "check_if_need_new_version",
    "_get_ecmwf_area",
    "_altitude_to_ecmwf_pressure",
    "_get_site_pressure",
]

_EXPORTS = {
    "cli": "._cli",
    "combine_and_elevate_inlet": "._combine",
    "combine_data_objects": "._combine",
    "combine_multisite": "._combine",
    "openghg_data_path": "._data",
    "format_data_level": "._data_level",
    "get_domain_info": "._domain",
    "find_domain": "._domain",
    "find_coord_name": "._domain",
    "convert_lon_to_180": "._domain",
    "convert_lon_to_360": "._domain",
    "convert_internal_longitude": "._domain",
    "cut_data_extent": "._domain",
    "align_lat_lon": "._domain",
    "download_data": "._download",
    "parse_url_filename": "._download",
    "to_dashboard": "._export",
    "to_dashboard_mobile": "._export",
    "check_filepath": "._file",
    "compress": "._file",
    "compress_json": "._file",
    "compress_str": "._file",
    "decompress": "._file",
    "decompress_json": "._file",
    "decompress_str": "._file",
    "get_datapath": "._file",
    "get_logfile_path": "._file",
    "load_json": "._file",
    "load_internal_json": "._file",
    "load_standardise_parser": "._file",
    "load_transform_parser": "._file",
    "read_header": "._file",
    "open_nc_fn": "._file",
    "open_time_nc_fn": "._file",
    "preprocess_nc_data": "._file",
    "get_data": "._file",
    "split_function_inputs": "._function_inputs",
    "format_inlet": "._inlet",
    "extract_inlet_value": "._inlet",
    "extract_height_name": "._inlet",
    "null_metadata_values": "._metadata_util",
    "not_set_metadata_values": "._metadata_util",
    "remove_null_keys": "._metadata_util",
    "check_number_match": "._metadata_util",
    "check_str_match": "._metadata_util",
    "check_value_match": "._metadata_util",
    "check_not_set_value": "._metadata_util",
    "get_overlap_keys": "._metadata_util",
    "merge_dict": "._metadata_util",
    "merge_and_extend_dict": "._metadata_util",
    "define_platform": "._platform",
    "format_platform": "._platform",
    "get_platform_from_info": "._platform",
    "get_parameters": "._registry",
    "AutoRegistry": "._registry",
    "Registry": "._registry",
    "update_scale": "._scale",
    "get_site_info": "._site",
    "sites_in_network": "._site",
    "_get_site_data": "._site",
    "get_species_info": "._species",
    "synonyms": "._species",
    "species_lifetime": "._species",
    "check_lifetime_monthly": "._species",
    "check_species_lifetime": "._species",
    "check_species_time_resolved": "._species",
    "molar_mass": "._species",
    "clean_string": "._strings",
    "extract_float": "._strings",
    "is_number": "._strings",
    "remove_punctuation": "._strings",
    "to_lowercase": "._strings",
    "check_and_set_null_variable": "._strings",
    "check_date": "._time",
    "check_nan": "._time",
    "closest_daterange": "._time",
    "combine_dateranges": "._time",
    "create_daterange": "._time",
    "create_daterange_str": "._time",
    "create_frequency_str": "._time",
    "daterange_contains": "._time",
    "daterange_from_str": "._time",
    "daterange_overlap": "._time",
    "dates_overlap": "._time",
    "daterange_to_str": "._time",
    "evaluate_sampling_period": "._time",
    "find_daterange_gaps": "._time",
    "find_duplicate_timestamps": "._time",
    "first_last_dates": "._time",
    "get_dataset_daterange": "._time",
    "get_representative_daterange_str": "._time",
    "in_daterange": "._time",
    "parse_period": "._time",
    "dates_in_range": "._time",
    "relative_time_offset": "._time",
    "has_monthly_period": "._time",
    "infer_frequency": "._time",
    "sanitise_daterange": "._time",
    "split_daterange_str": "._time",
    "split_encompassed_daterange": "._time",
    "time_offset": "._time",
    "time_offset_definition": "._time",
    "timestamp_epoch": "._time",
    "timestamp_now": "._time",
    "timestamp_tzaware": "._time",
    "trim_daterange": "._time",
    "valid_daterange": "._time",
    "create_config": "._user",
    "get_user_id": "._user",
    "get_user_config_path": "._user",
    "read_local_config": "._user",
    "check_config": "._user",
    "handle_direct_store_path": "._user",
    "find_matching_site": "._util",
    "normalise_to_filepath_list": "._util",
    "multiple_inlets": "._util",
    "pairwise": "._util",
    "site_code_finder": "._util",
    "sort_by_filenames": "._util",
    "unanimous": "._util",
    "verify_site": "._util",
    "verify_site_with_satellite": "._util",
    "check_unique": "._util",
    "find_repeats": "._util",
    "collate_strings": "._util",
    "assign_units": "._units",
    "cf_ureg": "._units",
    "enable_pint_xarray": "._units",
    "show_versions": "._versions",
    "check_if_need_new_version": "._versions",
    "_get_ecmwf_area": "._met",
    "_altitude_to_ecmwf_pressure": "._met",
    "_get_site_pressure": "._met",
}


def __getattr__(name: str) -> Any:
    """Lazily import utility helpers on first access."""
    try:
        module_name = _EXPORTS[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc

    value = getattr(_import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return the lazy public API for interactive introspection."""
    return sorted(__all__)
