direction: right

stand_fns -> standardise -> datatype_classes -> baseclass -> datasource

stand_fns: "Standardisation" {
  grid-columns: 1

  standardise_bc
  standardise_flux
  standardise_footprint
  standardise_column
  standardise_surface
  standardise_eulerian
  standardise_from_binary_data

}

standardise: "standardise"

datatype_classes: "Storage classes" {
  grid-columns: 2

  "BoundaryConditions.read_file"
  "Flux.read_file"
  "EulerianModel.read_file"
  "Footprints.read_file"
  "ObsColumn.read_file"
  "ObsSurface.read_file"
}

baseclass: "Base" {
  assign_data

}


datasource: "Datasource" {
  grid-columns: 1
  add_data
  add_metadata: {
    grid-columns: 1
    to_lowercase -> "self._metadata.update()"
  }

  add_data -> add_metadata

}