name: Manual Conda Build Push

on:
    push: 
      branches: "feature/**"
jobs:
    release_conda:
      name: Build and publish conda package
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash -el {0}
      steps:
        - uses: actions/checkout@v3
        - uses: mamba-org/setup-micromamba@875557da4ee020f18df03b8910a42203fbf02da1
          with:
            init-shell: bash
        - name: Build and push the conda package
          run: |
            micromamba create -n openghg_build anaconda-client boa conda-verify -c conda-forge
            micromamba activate openghg_build
            conda config --append channels openghg
            mkdir ${{ github.workspace }}/build
            conda mambabuild --croot ${{ github.workspace }}/build recipes -c conda-forge
            BUILD_DIR=${GITHUB_WORKSPACE}/build
            BUILD=$(find "$BUILD_DIR" -name '*.tar.bz2')
          env:
            ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
  