name: Create conda environment and run tests

on:
  push:
    branches: [master, devel]
    tags:
      - "*"
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    branches: [master, devel]
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  test:
    name: Run tests on (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment-dev.yaml
          cache-environment: true
          post-cleanup: "all"
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Install OpenGHG
        run: conda develop .
        shell: micromamba-shell {0}
      - name: Run the tests
        run: pytest -v tests/
        shell: micromamba-shell {0}
